[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3", "gcc", "pkg-config"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
