[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-optional"]

[start]
cmd = "npm run dev"

[variables]
NODE_ENV = "development"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
